services:
  db:
    image: mysql:8.0
    container_name: rentals_db
    environment:
      MYSQL_DATABASE: rentals
      MYSQL_USER: rentals
      MYSQL_PASSWORD: rentals123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: rentals_web
    environment:
      IN_DOCKER: "1"
      DB_ENGINE: "mysql"
      DB_HOST: "db"          # ВАЖНО: имя сервиса db
      DB_PORT: "3306"
      DB_NAME: "rentals"
      DB_USER: "rentals"
      DB_PASSWORD: "rentals123"
      DB_USE_SQLITE: "false"
      DEBUG: "true"
      ALLOWED_HOSTS: "127.0.0.1,localhost"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      sh -lc "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app

volumes:
  mysql_data:
