# Generated by Django 5.2.5 on 2025-08-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_updated_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_rating_2db6dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_created_bdcc91_idx',
        ),
    ]
