# Generated by Django 5.2.5 on 2025-08-19 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_property_type'),
        ('reviews', '0003_remove_review_reviews_rev_rating_2db6dd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('property', 'author'), name='unique_review_per_user_per_property'),
        ),
    ]
