# Generated by Django 5.2.5 on 2025-08-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HOST', 'Host'), ('TENANT', 'Tenant')], default='TENANT', max_length=16),
        ),
    ]
