# Generated by Django 5.2.5 on 2025-08-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_checkout_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('TENANT', 'Клиент'), ('OWNER', 'Владелец'), ('ADMIN', 'Админ')], max_length=10, null=True),
        ),
    ]
