# Generated by Django 5.2.5 on 2025-08-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cancelled_at_booking_cancelled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('APPROVED', 'Approved'), ('BOOKED', 'Booked'), ('IN_PROGRESS', 'In progress'), ('OVERDUE', 'Overdue'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=16),
        ),
    ]
