# Generated by Django 5.2.5 on 2025-08-20 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('properties', '0006_alter_property_property_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(default='interest', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='searchquery',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='viewevent',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewevent',
            name='referer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='viewevent',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='viewevent',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['created_at'], name='analytics_s_created_51dc01_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user', 'created_at'], name='analytics_s_user_id_a6be9e_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['session_key', 'created_at'], name='analytics_s_session_56a08a_idx'),
        ),
        migrations.AddIndex(
            model_name='viewevent',
            index=models.Index(fields=['property', 'created_at'], name='analytics_v_propert_3a87f9_idx'),
        ),
        migrations.AddIndex(
            model_name='viewevent',
            index=models.Index(fields=['session_key', 'created_at'], name='analytics_v_session_3eba9a_idx'),
        ),
        migrations.AddIndex(
            model_name='viewevent',
            index=models.Index(fields=['ip', 'created_at'], name='analytics_v_ip_82d73b_idx'),
        ),
        migrations.AddField(
            model_name='interestevent',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_events', to='properties.property'),
        ),
        migrations.AddField(
            model_name='interestevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='interestevent',
            index=models.Index(fields=['property', 'action', 'created_at'], name='analytics_i_propert_5eb4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='interestevent',
            index=models.Index(fields=['session_key', 'created_at'], name='analytics_i_session_7f28ad_idx'),
        ),
    ]
