# Generated by Django 5.2.5 on 2025-08-20 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_interestevent_searchquery_ip_searchquery_session_key_and_more'),
        ('properties', '0006_alter_property_property_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='viewevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='interestevent',
            name='analytics_i_propert_5eb4ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='interestevent',
            name='analytics_i_session_7f28ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchquery',
            name='analytics_s_user_id_a6be9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchquery',
            name='analytics_s_session_56a08a_idx',
        ),
        migrations.RemoveIndex(
            model_name='viewevent',
            name='analytics_v_propert_3a87f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='viewevent',
            name='analytics_v_session_3eba9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='viewevent',
            name='analytics_v_ip_82d73b_idx',
        ),
        migrations.RemoveField(
            model_name='interestevent',
            name='action',
        ),
        migrations.RemoveField(
            model_name='interestevent',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='interestevent',
            name='session_key',
        ),
        migrations.AddField(
            model_name='interestevent',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='viewevent',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='viewevent',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='interestevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_interest_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_search_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='referer',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_view_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='interestevent',
            index=models.Index(fields=['created_at'], name='analytics_i_created_ee5c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='interestevent',
            index=models.Index(fields=['kind'], name='analytics_i_kind_34fb9b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['session_key'], name='analytics_s_session_61f98e_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['ip'], name='analytics_s_ip_cfe272_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['query'], name='analytics_s_query_44edad_idx'),
        ),
        migrations.AddIndex(
            model_name='viewevent',
            index=models.Index(fields=['created_at'], name='analytics_v_created_046bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='viewevent',
            index=models.Index(fields=['session_key'], name='analytics_v_session_9cd2d5_idx'),
        ),
        migrations.AddIndex(
            model_name='viewevent',
            index=models.Index(fields=['ip'], name='analytics_v_ip_0826a9_idx'),
        ),
    ]
