# Generated by Django 5.2.5 on 2025-08-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
