# Generated by Django 5.2.5 on 2025-08-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyimage_address_line'),
    ]

    operations = [
    ]
from django.core.management.base import BaseCommand
from django.db import connection

class Command(BaseCommand):
    def handle(self, *args, **options):
        vendor = connection.vendor
        table = "properties_property"
        col = "address_line"
        with connection.cursor() as c:
            if vendor == "mysql":
                c.execute(
                    "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS "
                    "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME=%s",
                    [table, col],
                )
                exists = c.fetchone()[0] > 0
                if not exists:
                    c.execute(f"ALTER TABLE `{table}` ADD COLUMN `{col}` varchar(255) NOT NULL DEFAULT ''")
                    self.stdout.write("added address_line with DEFAULT ''")
                else:
                    c.execute(f"ALTER TABLE `{table}` MODIFY `{col}` varchar(255) NOT NULL DEFAULT ''")
                    self.stdout.write("modified address_line to NOT NULL DEFAULT ''")
            else:
                self.stdout.write("skip: not a MySQL database")
