# Generated by Django 5.2.5 on 2025-08-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyimage_address_line'),
        ('properties', '0004_fix_address_line'),
    ]

    operations = [
    ]
