# Generated by Django 5.2.5 on 2025-08-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_merge_20250814_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('STUDIO', 'Studio'), ('VILLA', 'Villa'), ('ROOM', 'Room')], max_length=20),
        ),
    ]
