# Generated by Django 5.2.5 on 2025-08-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
